version: '3.8'
services:
  postgres:
    container_name: acma-server
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: acma-server
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data