name: Unit Tests

on: [pull_requests]

jobs: 
  tests:
    runs-on: ubuntu-lastest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: action/checkout@v2
      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: unit tests
        run: npm run test:cov
      - name: build
        run: npm run build
